### ISSUE TITLE
QA Desserts Sprint

### ISSUE THREAD

**Issue by cathysnider** [cathysnider/hello-world#18]
- [x] Biscuits: Thin crispy apple cinnamon
- [x] Biscuits with honey and coconut flour
- [x] Biscuits with chocolate icing
- [x] Licorice fruitcake danish sesame snaps
- [x] Apple pie oat cake gingerbread cheesecake
- [x] Soufflé lollipop carrot cake chocolate cake
- [x] Cheesecake jujubes bear claw marzipan
- [x] Cupcake ipsum dolor sit
- [x] Pie gummi bears chocolate

**Comment by cathysnider** [comment]
&#10003;
